app: production
env: production
namespace: abs
chart:
  repository: https://chart.onechart.dev
  name: onechart
  version: 0.32.0
values:
  replicas: 2
strategicMergePatches: ""
json6902Patches: []
manifests: ""
