app: Zura
env: staging
namespace: staging
chart:
    repository: https://chart.onechart.dev
    name: onechart
    version: 0.32.0
values:
    containerPort: 1
    image:
        repository: newExample1231
        tag: 1.0.1
    ingress:
        annotations:
            newKey: New Value
            newKey-1: New Value
            newKey-2: New Value
            newKey-3: New Value
        host: ASD
    probe:
        enabled: true
        settings:
            failureThreshold: 8
            initialDelaySeconds: 75
            periodSeconds: 20
            successThreshold: 5
    replicas: 0
    resources:
        limits:
            cpu: 400m
            memory: 400Mi
        requests:
            cpu: 300m
            memory: 300Mi
    sealedSecrets:
        newKey-2: New Value
        newKey-3: New Value
    vars:
        newKey: New Value
        newKey-1: New Value
        newKey-2: New Value
        newKey-3: New Value
