app: Zura
env: staging
namespace: staging
chart:
    repository: https://chart.onechart.dev
    name: onechart
    version: 0.32.0
values:
    containerPort: 801
    image:
        repository: example123
        tag: 1.19.3
    ingress:
        annotations:
            newKey: New Value
            newKey-1: New Value
        host: ""
        tlsEnabled: false
    podDisruptionBudgetEnabled: true
    probe:
        enabled: false
        path: /
        settings:
            failureThreshold: 3
            initialDelaySeconds: 0
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 3
    replicas: 6
    resources:
        limits:
            cpu: 500m
            memory: 500Mi
        requests:
            cpu: 500m
            memory: 500Mi
    sealedSecrets:
        newKey: New Value
        newKey-1: New Value
        newKey-2: New Value
        newKey-3: New Value
    spreadAcrossNodes: false
    vars:
        newKey: New Value
        newKey-1: New Value
        newKey-2: New Value
        newKey-3: New Value
    volumes:
        - name: data123
          path: /data
          size: 10Gi
          storageClass: ""
