app: staging
env: staging
namespace: default
chart:
  repository: https://chart.onechart.dev
  name: onechart
  version: 0.32.0
values:
  gitRepository: szabogabor91/Zura
  gitSha: '{{ .GITHUB_SHA }}'
  replicas: 2
strategicMergePatches: ""
json6902Patches: []
manifests: ""
